In [3]:
%pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.22.0rc0-cp314-cp314-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow) (26.3)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting requests<3,>=2.21.0 (from tensorflow)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow) (4.16.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.4.1-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.84.0-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Collecting keras-nightly>=3.12.0.dev (from tensorflow)
  Downloading keras_nightly-3.16.0.dev2026092504-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in .\venv\Lib\site-packages (from tensorflow) (2.5.2)
Collecting h5py~=3.15.1 (from tensorflow)
  Downloading h5py-3.15.1-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.6.0-cp314-cp314-win_amd64.whl.metadata (8.8 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorflow)
  Downloading charset_normalizer-3.5.1-cp314-cp314-win_amd64.whl.metadata (46 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorflow)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.21.0->tensorflow)
  Downloading urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.21.0->tensorflow)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras-nightly>=3.12.0.dev->tensorflow)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras-nightly>=3.12.0.dev->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras-nightly>=3.12.0.dev->tensorflow)
  Downloading optree-0.20.0-cp314-cp314-win_amd64.whl.metadata (33 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras-nightly>=3.12.0.dev->tensorflow)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv\Lib\site-packages (from rich->keras-nightly>=3.12.0.dev->tensorflow) (2.21.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras-nightly>=3.12.0.dev->tensorflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.22.0rc0-cp314-cp314-win_amd64.whl (384.1 MB)
   ---------------------------------------- 0.0/384.1 MB ? eta -:--:--
   ---------------------------------------- 2.4/384.1 MB 11.2 MB/s eta 0:00:35
   ---------------------------------------- 4.7/384.1 MB 11.3 MB/s eta 0:00:34
    --------------------------------------- 7.1/384.1 MB 11.4 MB/s eta 0:00:33
   - -------------------------------------- 9.7/384.1 MB 11.6 MB/s eta 0:00:33
   - -------------------------------------- 12.1/384.1 MB 11.6 MB/s eta 0:00:33
   - -------------------------------------- 14.4/384.1 MB 11.6 MB/s eta 0:00:32
   - -------------------------------------- 16.8/384.1 MB 11.6 MB/s eta 0:00:32
   - -------------------------------------- 19.1/384.1 MB 11.6 MB/s eta 0:00:32
   -- ------------------------------------- 21.8/384.1 MB 11.6 MB/s eta 0:00:32
   -- ------------------------------------- 24.1/384.1 MB 11.6 MB/s eta 0:00:31
   -- ------------------------------------- 26.5/384.1 MB 11.6 MB/s eta 0:00:31
   -- ------------------------------------- 28.0/384.1 MB 11.3 MB/s eta 0:00:32
   --- ------------------------------------ 30.4/384.1 MB 11.2 MB/s eta 0:00:32
   --- ------------------------------------ 32.8/384.1 MB 11.3 MB/s eta 0:00:32
   --- ------------------------------------ 35.4/384.1 MB 11.3 MB/s eta 0:00:31
   --- ------------------------------------ 37.7/384.1 MB 11.3 MB/s eta 0:00:31
   ---- ----------------------------------- 40.1/384.1 MB 11.3 MB/s eta 0:00:31
   ---- ----------------------------------- 42.7/384.1 MB 11.4 MB/s eta 0:00:31
   ---- ----------------------------------- 45.4/384.1 MB 11.4 MB/s eta 0:00:30
   ---- ----------------------------------- 48.0/384.1 MB 11.4 MB/s eta 0:00:30
   ----- ---------------------------------- 50.3/384.1 MB 11.4 MB/s eta 0:00:30
   ----- ---------------------------------- 53.0/384.1 MB 11.5 MB/s eta 0:00:29
   ----- ---------------------------------- 55.3/384.1 MB 11.4 MB/s eta 0:00:29
   ------ --------------------------------- 57.7/384.1 MB 11.5 MB/s eta 0:00:29
   ------ --------------------------------- 60.3/384.1 MB 11.5 MB/s eta 0:00:29
   ------ --------------------------------- 62.9/384.1 MB 11.5 MB/s eta 0:00:28
   ------ --------------------------------- 64.7/384.1 MB 11.4 MB/s eta 0:00:28
   ------ --------------------------------- 66.8/384.1 MB 11.3 MB/s eta 0:00:29
   ------- -------------------------------- 69.2/384.1 MB 11.3 MB/s eta 0:00:28
   ------- -------------------------------- 71.6/384.1 MB 11.4 MB/s eta 0:00:28
   ------- -------------------------------- 74.2/384.1 MB 11.4 MB/s eta 0:00:28
   ------- -------------------------------- 76.8/384.1 MB 11.4 MB/s eta 0:00:27
   -------- ------------------------------- 78.9/384.1 MB 11.3 MB/s eta 0:00:27
   -------- ------------------------------- 81.0/384.1 MB 11.3 MB/s eta 0:00:27
   -------- ------------------------------- 83.1/384.1 MB 11.3 MB/s eta 0:00:27
   -------- ------------------------------- 85.2/384.1 MB 11.2 MB/s eta 0:00:27
   --------- ------------------------------ 86.8/384.1 MB 11.2 MB/s eta 0:00:27
   --------- ------------------------------ 87.0/384.1 MB 10.9 MB/s eta 0:00:28
   --------- ------------------------------ 88.9/384.1 MB 10.8 MB/s eta 0:00:28
   --------- ------------------------------ 91.5/384.1 MB 10.8 MB/s eta 0:00:27
   --------- ------------------------------ 93.8/384.1 MB 10.9 MB/s eta 0:00:27
   ---------- ----------------------------- 96.5/384.1 MB 10.9 MB/s eta 0:00:27
   ---------- ----------------------------- 98.8/384.1 MB 10.9 MB/s eta 0:00:27
   ---------- ---------------------------- 101.4/384.1 MB 10.9 MB/s eta 0:00:26
   ---------- ---------------------------- 103.8/384.1 MB 10.9 MB/s eta 0:00:26
   ---------- ---------------------------- 105.9/384.1 MB 10.9 MB/s eta 0:00:26
   ---------- ---------------------------- 108.3/384.1 MB 10.9 MB/s eta 0:00:26
   ----------- --------------------------- 110.4/384.1 MB 10.9 MB/s eta 0:00:26
   ----------- --------------------------- 112.5/384.1 MB 10.9 MB/s eta 0:00:25
   ----------- --------------------------- 114.6/384.1 MB 10.8 MB/s eta 0:00:25
   ----------- --------------------------- 116.9/384.1 MB 10.8 MB/s eta 0:00:25
   ------------ -------------------------- 118.8/384.1 MB 10.8 MB/s eta 0:00:25
   ------------ -------------------------- 121.1/384.1 MB 10.8 MB/s eta 0:00:25
   ------------ -------------------------- 122.9/384.1 MB 10.8 MB/s eta 0:00:25
   ------------ -------------------------- 125.3/384.1 MB 10.8 MB/s eta 0:00:25
   ------------ -------------------------- 127.4/384.1 MB 10.7 MB/s eta 0:00:24
   ------------- ------------------------- 129.5/384.1 MB 10.7 MB/s eta 0:00:24
   ------------- ------------------------- 131.6/384.1 MB 10.7 MB/s eta 0:00:24
   ------------- ------------------------- 133.7/384.1 MB 10.7 MB/s eta 0:00:24
   ------------- ------------------------- 135.8/384.1 MB 10.7 MB/s eta 0:00:24
   -------------- ------------------------ 137.9/384.1 MB 10.7 MB/s eta 0:00:24
   -------------- ------------------------ 140.2/384.1 MB 10.7 MB/s eta 0:00:23
   -------------- ------------------------ 142.3/384.1 MB 10.7 MB/s eta 0:00:23
   -------------- ------------------------ 144.4/384.1 MB 10.6 MB/s eta 0:00:23
   -------------- ------------------------ 146.3/384.1 MB 10.6 MB/s eta 0:00:23
   --------------- ----------------------- 148.6/384.1 MB 10.6 MB/s eta 0:00:23
   --------------- ----------------------- 150.7/384.1 MB 10.6 MB/s eta 0:00:23
   --------------- ----------------------- 152.3/384.1 MB 10.6 MB/s eta 0:00:22
   --------------- ----------------------- 154.7/384.1 MB 10.6 MB/s eta 0:00:22
   --------------- ----------------------- 157.0/384.1 MB 10.6 MB/s eta 0:00:22
   ---------------- ---------------------- 159.1/384.1 MB 10.6 MB/s eta 0:00:22
   ---------------- ---------------------- 161.2/384.1 MB 10.6 MB/s eta 0:00:22
   ---------------- ---------------------- 163.3/384.1 MB 10.6 MB/s eta 0:00:21
   ---------------- ---------------------- 165.4/384.1 MB 10.5 MB/s eta 0:00:21
   ----------------- --------------------- 167.5/384.1 MB 10.5 MB/s eta 0:00:21
   ----------------- --------------------- 169.6/384.1 MB 10.5 MB/s eta 0:00:21
   ----------------- --------------------- 171.4/384.1 MB 10.5 MB/s eta 0:00:21
   ----------------- --------------------- 173.3/384.1 MB 10.5 MB/s eta 0:00:21
   ----------------- --------------------- 175.9/384.1 MB 10.5 MB/s eta 0:00:20
   ------------------ -------------------- 178.0/384.1 MB 10.5 MB/s eta 0:00:20
   ------------------ -------------------- 179.8/384.1 MB 10.5 MB/s eta 0:00:20
   ------------------ -------------------- 182.2/384.1 MB 10.5 MB/s eta 0:00:20
   ------------------ -------------------- 184.0/384.1 MB 10.5 MB/s eta 0:00:20
   ------------------ -------------------- 186.4/384.1 MB 10.5 MB/s eta 0:00:19
   ------------------- ------------------- 188.7/384.1 MB 10.5 MB/s eta 0:00:19
   ------------------- ------------------- 190.8/384.1 MB 10.5 MB/s eta 0:00:19
   ------------------- ------------------- 192.9/384.1 MB 10.5 MB/s eta 0:00:19
   ------------------- ------------------- 194.8/384.1 MB 10.4 MB/s eta 0:00:19
   ------------------- ------------------- 196.9/384.1 MB 10.4 MB/s eta 0:00:18
   -------------------- ------------------ 199.5/384.1 MB 10.4 MB/s eta 0:00:18
   -------------------- ------------------ 201.6/384.1 MB 10.4 MB/s eta 0:00:18
   -------------------- ------------------ 203.7/384.1 MB 10.4 MB/s eta 0:00:18
   -------------------- ------------------ 205.8/384.1 MB 10.4 MB/s eta 0:00:18
   --------------------- ----------------- 207.9/384.1 MB 10.4 MB/s eta 0:00:17
   --------------------- ----------------- 210.0/384.1 MB 10.4 MB/s eta 0:00:17
   --------------------- ----------------- 212.1/384.1 MB 10.4 MB/s eta 0:00:17
   --------------------- ----------------- 214.2/384.1 MB 10.4 MB/s eta 0:00:17
   --------------------- ----------------- 216.5/384.1 MB 10.4 MB/s eta 0:00:17
   ---------------------- ---------------- 218.6/384.1 MB 10.4 MB/s eta 0:00:16
   ---------------------- ---------------- 220.5/384.1 MB 10.4 MB/s eta 0:00:16
   ---------------------- ---------------- 222.8/384.1 MB 10.4 MB/s eta 0:00:16
   ---------------------- ---------------- 224.7/384.1 MB 10.4 MB/s eta 0:00:16
   ----------------------- --------------- 227.0/384.1 MB 10.4 MB/s eta 0:00:16
   ----------------------- --------------- 228.9/384.1 MB 10.3 MB/s eta 0:00:16
   ----------------------- --------------- 230.9/384.1 MB 10.3 MB/s eta 0:00:15
   ----------------------- --------------- 232.5/384.1 MB 10.3 MB/s eta 0:00:15
   ----------------------- --------------- 234.6/384.1 MB 10.3 MB/s eta 0:00:15
   ------------------------ -------------- 237.0/384.1 MB 10.3 MB/s eta 0:00:15
   ------------------------ -------------- 239.3/384.1 MB 10.3 MB/s eta 0:00:15
   ------------------------ -------------- 241.7/384.1 MB 10.3 MB/s eta 0:00:14
   ------------------------ -------------- 244.1/384.1 MB 10.3 MB/s eta 0:00:14
   ------------------------ -------------- 246.2/384.1 MB 10.3 MB/s eta 0:00:14
   ------------------------- ------------- 248.3/384.1 MB 10.3 MB/s eta 0:00:14
   ------------------------- ------------- 250.1/384.1 MB 10.3 MB/s eta 0:00:13
   ------------------------- ------------- 252.4/384.1 MB 10.3 MB/s eta 0:00:13
   ------------------------- ------------- 254.5/384.1 MB 10.3 MB/s eta 0:00:13
   -------------------------- ------------ 256.9/384.1 MB 10.3 MB/s eta 0:00:13
   -------------------------- ------------ 259.0/384.1 MB 10.3 MB/s eta 0:00:13
   -------------------------- ------------ 261.1/384.1 MB 10.3 MB/s eta 0:00:12
   -------------------------- ------------ 263.2/384.1 MB 10.3 MB/s eta 0:00:12
   -------------------------- ------------ 265.3/384.1 MB 10.3 MB/s eta 0:00:12
   --------------------------- ----------- 267.4/384.1 MB 10.3 MB/s eta 0:00:12
   --------------------------- ----------- 269.5/384.1 MB 10.3 MB/s eta 0:00:12
   --------------------------- ----------- 271.6/384.1 MB 10.2 MB/s eta 0:00:11
   --------------------------- ----------- 273.7/384.1 MB 10.2 MB/s eta 0:00:11
   ---------------------------- ---------- 275.8/384.1 MB 10.2 MB/s eta 0:00:11
   ---------------------------- ---------- 277.3/384.1 MB 10.2 MB/s eta 0:00:11
   ---------------------------- ---------- 280.0/384.1 MB 10.2 MB/s eta 0:00:11
   ---------------------------- ---------- 282.1/384.1 MB 10.2 MB/s eta 0:00:11
   ---------------------------- ---------- 284.2/384.1 MB 10.2 MB/s eta 0:00:10
   ----------------------------- --------- 286.5/384.1 MB 10.2 MB/s eta 0:00:10
   ----------------------------- --------- 288.6/384.1 MB 10.2 MB/s eta 0:00:10
   ----------------------------- --------- 290.7/384.1 MB 10.2 MB/s eta 0:00:10
   ----------------------------- --------- 292.8/384.1 MB 10.2 MB/s eta 0:00:09
   ----------------------------- --------- 294.9/384.1 MB 10.1 MB/s eta 0:00:09
   ------------------------------ -------- 297.0/384.1 MB 10.1 MB/s eta 0:00:09
   ------------------------------ -------- 299.1/384.1 MB 10.1 MB/s eta 0:00:09
   ------------------------------ -------- 301.2/384.1 MB 10.1 MB/s eta 0:00:09
   ------------------------------ -------- 303.3/384.1 MB 10.1 MB/s eta 0:00:09
   ------------------------------- ------- 305.4/384.1 MB 10.1 MB/s eta 0:00:08
   ------------------------------- ------- 307.0/384.1 MB 10.1 MB/s eta 0:00:08
   ------------------------------- ------- 309.3/384.1 MB 10.0 MB/s eta 0:00:08
   ------------------------------- ------- 312.0/384.1 MB 10.0 MB/s eta 0:00:08
   ------------------------------- ------- 313.8/384.1 MB 10.0 MB/s eta 0:00:08
   ------------------------------- ------- 314.8/384.1 MB 10.0 MB/s eta 0:00:07
   -------------------------------- ------- 315.9/384.1 MB 9.9 MB/s eta 0:00:07
   --------------------------------- ------ 317.7/384.1 MB 9.9 MB/s eta 0:00:07
   --------------------------------- ------ 320.1/384.1 MB 9.9 MB/s eta 0:00:07
   --------------------------------- ------ 322.7/384.1 MB 9.9 MB/s eta 0:00:07
   --------------------------------- ------ 325.3/384.1 MB 9.9 MB/s eta 0:00:06
   ---------------------------------- ----- 327.7/384.1 MB 9.9 MB/s eta 0:00:06
   --------------------------------- ----- 330.3/384.1 MB 10.0 MB/s eta 0:00:06
   --------------------------------- ----- 332.9/384.1 MB 10.0 MB/s eta 0:00:06
   ---------------------------------- ----- 334.8/384.1 MB 9.9 MB/s eta 0:00:05
   ----------------------------------- ---- 337.1/384.1 MB 9.9 MB/s eta 0:00:05
   ----------------------------------- ---- 339.2/384.1 MB 9.9 MB/s eta 0:00:05
   ----------------------------------- ---- 341.3/384.1 MB 9.9 MB/s eta 0:00:05
   ----------------------------------- ---- 343.4/384.1 MB 9.9 MB/s eta 0:00:05
   ----------------------------------- ---- 345.5/384.1 MB 9.9 MB/s eta 0:00:04
   ------------------------------------ --- 347.3/384.1 MB 9.9 MB/s eta 0:00:04
   ----------------------------------- --- 349.7/384.1 MB 10.0 MB/s eta 0:00:04
   ----------------------------------- --- 351.8/384.1 MB 10.0 MB/s eta 0:00:04
   ----------------------------------- --- 353.9/384.1 MB 10.0 MB/s eta 0:00:04
   ------------------------------------ -- 356.0/384.1 MB 10.0 MB/s eta 0:00:03
   ------------------------------------ -- 357.8/384.1 MB 10.0 MB/s eta 0:00:03
   ------------------------------------- -- 359.4/384.1 MB 9.9 MB/s eta 0:00:03
   ------------------------------------- -- 362.0/384.1 MB 9.9 MB/s eta 0:00:03
   ------------------------------------- -- 363.6/384.1 MB 9.9 MB/s eta 0:00:03
   -------------------------------------- - 364.9/384.1 MB 9.9 MB/s eta 0:00:02
   -------------------------------------- - 367.0/384.1 MB 9.9 MB/s eta 0:00:02
   -------------------------------------- - 369.4/384.1 MB 9.9 MB/s eta 0:00:02
   -------------------------------------- - 372.0/384.1 MB 9.9 MB/s eta 0:00:02
   ---------------------------------------  374.6/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  377.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  379.1/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  381.2/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  383.5/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  384.0/384.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------- 384.1/384.1 MB 8.6 MB/s  0:00:41
Downloading grpcio-1.84.0-cp314-cp314-win_amd64.whl (5.4 MB)
   ---------------------------------------- 0.0/5.4 MB ? eta -:--:--
   --------------- ------------------------ 2.1/5.4 MB 11.2 MB/s eta 0:00:01
   ---------------------------------- ----- 4.7/5.4 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------- 5.4/5.4 MB 10.2 MB/s  0:00:00

In [4]:
## Check version
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.22.0-rc0

In [5]:
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [6]:
## Load the ANN trained model, scaler pickle, one hot encoder
model = load_model('model.h5')

## Load the encoders and scalers
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)
with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
e:\ANN\annclassification\venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.7.2 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
e:\ANN\annclassification\venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.7.2 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
e:\ANN\annclassification\venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.7.2 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [28]:
## Example input data for prediction
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [29]:
## One hot encode the 'Geography' feature
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

e:\ANN\annclassification\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [30]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [31]:
## Encode categorical features
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [32]:
## Concatenate the one hot encoded 'Geography' features with the rest of the input data
input_df = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [33]:
### Scaling the input data using the previously fitted scaler
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [35]:
## Predict the output using the trained ANN model
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

array([[0.03378703]], dtype=float32)

In [36]:
prediction_proba = prediction[0][0]

In [37]:
prediction_proba

np.float32(0.033787027)

In [38]:
if prediction_proba > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is unlikely to churn.")

The customer is unlikely to churn.