In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocessing the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
## Encode Categorical variables
Label_Encoder_Gender = LabelEncoder()
data['Gender'] = Label_Encoder_Gender.fit_transform(data['Gender'])

In [7]:
## OneHotEncoding the Geography column
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
## Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
Y = data['EstimatedSalary']

In [10]:
## Split the data in training and testing sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [11]:
## Scaling the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
## Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(Label_Encoder_Gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Regression Problem Statement

In [13]:
%pip install tensorboard

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.11)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (2.5.2)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (84.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
## Build the ANN model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), ## Hidden Layer 1 connected with input layer
    Dense(32, activation='relu'), ## Hidden Layer 2
    Dense(1) ## Output Layer for regression ## The default activation function will be linear activation function ## Linear activation function is basically used for regression.
]
)

## Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

e:\ANN\annclassification\venv\Lib\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
## Set up the TensorBoard callback
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime


## Setup Tensorboard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1) ## Visualize the model training in TensorBoard

In [17]:
## Set up early stopping and TensorBoard callbacks
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [18]:
### Train the model
history=model.fit(
    X_train,Y_train,
    validation_data=(X_test,Y_test),
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
    )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100393.1875 - mae: 100393.1875 - val_loss: 98575.6328 - val_mae: 98575.6328
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99836.5156 - mae: 99836.5156 - val_loss: 97443.5078 - val_mae: 97443.5078
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97835.3125 - mae: 97835.3125 - val_loss: 94492.4609 - val_mae: 94492.4609
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93812.9141 - mae: 93812.9141 - val_loss: 89437.2031 - val_mae: 89437.2031
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 87758.0469 - mae: 87758.0469 - val_loss: 82618.6016 - val_mae: 82618.6016
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 80188.4766 - mae: 80188.4766 - val_loss: 74810.5156 - val_mae: 74810.5156
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 72101.7891 - mae: 72101.7891 - val_loss: 67257.3750 - val_mae: 67257.3750
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 64605.5078 - mae: 64605.5078 - val_loss: 60848.8086 - val_mae: 60848.8086
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 58695.3867 - mae: 58695.3867 - val_loss: 56197.6016 - val_mae: 56197.6016
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54716.6719 - mae: 54716.6719 - val_loss: 53352.9258 - val_mae: 53352.9258
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52398.7734 - mae: 52398.7734 - val_loss: 51915.8555 - val_mae: 51915.8555
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51288.8555 - mae: 51288.8555 - val_loss: 51373.0742 - val_mae: 51373.0742
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50815.2656 - mae: 50815.2656 - val_loss: 51172.8320 - val_mae: 51172.8320
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50611.7344 - mae: 50611.7344 - val_loss: 51074.0312 - val_mae: 51074.0312
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50503.3359 - mae: 50503.3359 - val_loss: 51000.7148 - val_mae: 51000.7148
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50424.1875 - mae: 50424.1875 - val_loss: 50938.4453 - val_mae: 50938.4453
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50358.7070 - mae: 50358.7070 - val_loss: 50879.1914 - val_mae: 50879.1914
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50301.3711 - mae: 50301.3711 - val_loss: 50826.9648 - val_mae: 50826.9648
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50249.6797 - mae: 50249.6797 - val_loss: 50779.2031 - val_mae: 50779.2031
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50203.8789 - mae: 50203.8789 - val_loss: 50733.6250 - val_mae: 50733.6250
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50163.0430 - mae: 50163.0430 - val_loss: 50694.9297 - val_mae: 50694.9297
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50125.2617 - mae: 50125.2617 - val_loss: 50657.6055 - val_mae: 50657.6055
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50089.4453 - mae: 50089.4453 - val_loss: 50623.6289 - val_mae: 50623.6289
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50056.5938 - mae: 50056.5938 - val_loss: 50590.2656 - val_mae: 50590.2656
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50025.3672 - mae: 50025.3672 - val_loss: 50561.3672 - val_mae: 50561.3672
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49996.3438 - mae: 49996.3438 - val_loss: 50535.8672 - val_mae: 50535.8672
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49968.4688 - mae: 49968.4688 - val_loss: 50512.1562 - val_mae: 50512.1562
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49941.6445 - mae: 49941.6445 - val_loss: 50492.0156 - val_mae: 50492.0156
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49916.7773 - mae: 49916.7773 - val_loss: 50470.9219 - val_mae: 50470.9219
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49892.3438 - mae: 49892.3438 - val_loss: 50451.8711 - val_mae: 50451.8711
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49869.1914 - mae: 49869.1914 - val_loss: 50434.8008 - val_mae: 50434.8008
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49847.9453 - mae: 49847.9453 - val_loss: 50419.1016 - val_mae: 50419.1016
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49828.0586 - mae: 49828.0586 - val_loss: 50403.5078 - val_mae: 50403.5078
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49809.3281 - mae: 49809.3281 - val_loss: 50389.5469 - val_mae: 50389.5469
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49791.6055 - mae: 49791.6055 - val_loss: 50376.4570 - val_mae: 50376.4570
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49774.7734 - mae: 49774.7734 - val_loss: 50366.3867 - val_mae: 50366.3867
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49758.1680 - mae: 49758.1680 - val_loss: 50354.7031 - val_mae: 50354.7031
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49742.6641 - mae: 49742.6641 - val_loss: 50342.6562 - val_mae: 50342.6562
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49727.9375 - mae: 49727.9375 - val_loss: 50330.2617 - val_mae: 50330.2617
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49713.8047 - mae: 49713.8047 - val_loss: 50321.1562 - val_mae: 50321.1562
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49700.2305 - mae: 49700.2305 - val_loss: 50313.1211 - val_mae: 50313.1211
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49687.7617 - mae: 49687.7617 - val_loss: 50305.1602 - val_mae: 50305.1602
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49675.4375 - mae: 49675.4375 - val_loss: 50297.0859 - val_mae: 50297.0859
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49663.7422 - mae: 49663.7422 - val_loss: 50289.2852 - val_mae: 50289.2852
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49652.8633 - mae: 49652.8633 - val_loss: 50281.1836 - val_mae: 50281.1836
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49642.9414 - mae: 49642.9414 - val_loss: 50277.4570 - val_mae: 50277.4570
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49633.6172 - mae: 49633.6172 - val_loss: 50271.8906 - val_mae: 50271.8906
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49624.8867 - mae: 49624.8867 - val_loss: 50266.9609 - val_mae: 50266.9609
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49616.1602 - mae: 49616.1602 - val_loss: 50262.3594 - val_mae: 50262.3594
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49607.6133 - mae: 49607.6133 - val_loss: 50258.6328 - val_mae: 50258.6328
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49599.1367 - mae: 49599.1367 - val_loss: 50252.6016 - val_mae: 50252.6016
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49591.2734 - mae: 49591.2734 - val_loss: 50247.9727 - val_mae: 50247.9727
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49583.7109 - mae: 49583.7109 - val_loss: 50244.2852 - val_mae: 50244.2852
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49576.2070 - mae: 49576.2070 - val_loss: 50242.1719 - val_mae: 50242.1719
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49569.0469 - mae: 49569.0469 - val_loss: 50240.1836 - val_mae: 50240.1836
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49562.0547 - mae: 49562.0547 - val_loss: 50238.1484 - val_mae: 50238.1484
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49555.4688 - mae: 49555.4688 - val_loss: 50235.6289 - val_mae: 50235.6289
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49549.0625 - mae: 49549.0625 - val_loss: 50234.0977 - val_mae: 50234.0977
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49542.6484 - mae: 49542.6484 - val_loss: 50232.1641 - val_mae: 50232.1641
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49536.5234 - mae: 49536.5234 - val_loss: 50230.4102 - val_mae: 50230.4102
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49530.5938 - mae: 49530.5938 - val_loss: 50228.6719 - val_mae: 50228.6719
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49524.4961 - mae: 49524.4961 - val_loss: 50228.0156 - val_mae: 50228.0156
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518.8320 - mae: 49518.8320 - val_loss: 50228.1953 - val_mae: 50228.1953
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49513.3828 - mae: 49513.3828 - val_loss: 50228.2578 - val_mae: 50228.2578
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49507.9297 - mae: 49507.9297 - val_loss: 50227.5156 - val_mae: 50227.5156
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49502.9023 - mae: 49502.9023 - val_loss: 50227.0781 - val_mae: 50227.0781
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49497.7852 - mae: 49497.7852 - val_loss: 50225.1172 - val_mae: 50225.1172
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49492.8242 - mae: 49492.8242 - val_loss: 50223.5156 - val_mae: 50223.5156
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49487.8477 - mae: 49487.8477 - val_loss: 50223.9102 - val_mae: 50223.9102
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49482.8828 - mae: 49482.8828 - val_loss: 50225.1562 - val_mae: 50225.1562
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49477.9648 - mae: 49477.9648 - val_loss: 50225.2383 - val_mae: 50225.2383
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49473.0938 - mae: 49473.0938 - val_loss: 50224.7344 - val_mae: 50224.7344
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49468.1602 - mae: 49468.1602 - val_loss: 50225.2852 - val_mae: 50225.2852
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49463.3672 - mae: 49463.3672 - val_loss: 50223.6445 - val_mae: 50223.6445
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49458.5703 - mae: 49458.5703 - val_loss: 50224.5859 - val_mae: 50224.5859
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49453.9336 - mae: 49453.9336 - val_loss: 50224.6094 - val_mae: 50224.6094
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49449.5859 - mae: 49449.5859 - val_loss: 50225.7578 - val_mae: 50225.7578
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49445.3750 - mae: 49445.3750 - val_loss: 50226.6680 - val_mae: 50226.6680

In [19]:
### Evaluate the model
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 26092), started 13:33:41 ago. (Use '!kill 26092' to kill it.)

In [21]:
## Evaluate model on the test data
test_loss,test_mae = model.evaluate(X_test,Y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50223.5156 - mae: 50223.5156
Test MAE: 50223.515625

In [22]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.